language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.8
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=cov

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.10
    - python: "3.3"
      env: DJANGO=1.11
    - python: "3.3"
      env: DJANGO=cov
    - python: "3.4"
      env: DJANGO=cov
    - python: "3.5"
      env: DJANGO=cov
    - python: "3.6"
      env: DJANGO=1.8
    - python: "3.6"
      env: DJANGO=1.10
    - python: "3.6"
      env: DJANGO=cov

install:
  - pip install tox coveralls

script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-${DJANGO//[.]/}
after_success:
  - coveralls
